let datos={perfil:{},ofertas:[]}, timer, sequence=0;
const $=id=>document.getElementById(id), filters=$('filtros');
const nombres={practicas:'Prácticas.pe',convocatorias:'Convocatorias de Trabajo',linkedin:'LinkedIn',manual:'Importadas'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function prefs(){const f=new FormData(filters);return {...Object.fromEntries(f),fuentes:f.getAll('fuentes'),sinfecha:f.has('sinfecha'),desconocidos:f.has('desconocidos'),vencidas:f.has('vencidas'),orden:$('orden').value};}
async function api(path,body){const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar');return d;}
function fill(form,values){for(const [k,v]of Object.entries(values)){form.querySelectorAll(`[name="${k}"]`).forEach(c=>{if(c.type==='checkbox')c.checked=Array.isArray(v)?v.includes(c.value):!!v;else c.value=v??'';});}}
function tarjeta(j,alternativa=false){return `<article class="card"><div class="meta"><span class="source">${esc(nombres[j.fuente])}</span><span>${esc(j.estado)}</span></div><h3>${esc(j.titulo)}</h3><div class="meta"><span>${esc(j.empresa||'Empresa por confirmar')}</span><span>${esc(j.ubicacion||'Ubicación por confirmar')}</span><span>${esc(j.modalidad||'Modalidad por confirmar')}</span><span>${esc(j.tipo==='practicas'?'Prácticas · nivel por confirmar':j.tipo)}</span></div>${alternativa?`<p class="outside">Fuera de tus filtros: ${esc(j.excluida_por.join(', '))}</p>`:''}<div class="dates"><span>${j.antiguedad===null?'Publicación: fecha desconocida':`Publicado hace ${Math.floor(j.antiguedad)} días`}</span><span>${j.cierre?`Cierre: ${esc(j.cierre.slice(0,10))}${j.cierre.length>10?' · '+esc(j.cierre.slice(11,16))+' h':''}`:'Cierre: sin fecha confirmada'}</span>${j.salario!=null?`<span>Sueldo: ${esc(j.moneda)} ${esc(j.salario)} · ${esc(j.periodo)}</span>`:''}</div><div class="match">${j.puntaje===null?'Completa tu perfil para recibir recomendaciones':`${j.puntaje}/100 · compatibilidad orientativa`}</div>${j.razones.length?`<ul class="reasons">${j.razones.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`:''}${j.requisitos.length?`<div class="checks">${j.requisitos.map(c=>`<div><strong class="${c.estado==='brecha'?'gap':''}">${esc(c.nombre)} · ${esc(c.estado)}</strong><p>${esc(c.evidencia)}</p></div>`).join('')}</div>`:''}<p class="hint">${esc(j.aviso)}</p><details><summary>Revisar descripción y requisitos</summary><p class="description">${esc(j.descripcion||'La fuente no proporcionó descripción. Revisa el anuncio original.')}</p></details><div class="cardactions">${/^https?:\/\//i.test(j.url)?`<a href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">Ver anuncio original</a>`:''}<button type="button" class="secondary ${j.valoracion==='interesa'?'selected':''}" data-id="${esc(j.id)}" data-vote="interesa" aria-pressed="${j.valoracion==='interesa'}">Me interesa</button><button type="button" class="secondary ${j.valoracion==='no_interesa'?'selected':''}" data-id="${esc(j.id)}" data-vote="no_interesa" aria-pressed="${j.valoracion==='no_interesa'}">No me interesa</button>${j.valoracion?`<button type="button" class="secondary" data-id="${esc(j.id)}" data-vote="">Deshacer valoración</button>`:''}</div></article>`;}
function render(){
 $('cantidad').textContent=`${datos.ofertas.length} visibles · ${datos.total} guardadas`;
 $('diagnostico').innerHTML=`<div class="sourcecounts">${Object.entries(datos.fuentes||{}).map(([s,c])=>`<span><strong>${esc(nombres[s])}</strong> ${c.visibles} visibles / ${c.guardadas} guardadas</span>`).join('')}</div>${Object.keys(datos.ocultas||{}).length?`<p class="hint">Ocultas por tus filtros: ${Object.entries(datos.ocultas).map(([k,v])=>esc(k)+': '+v).join(' · ')}. Una oferta puede incumplir varios filtros.</p>`:''}`;
 $('aprendizaje').textContent=datos.valoraciones?`Aprendizaje local: ${datos.valoraciones} ofertas valoradas. Puedes deshacer cada valoración.`:'El orden se personaliza con tu perfil. “Me interesa” y “No me interesa” enseñan qué oportunidades prefieres.';
 $('ofertas').innerHTML=datos.ofertas.length?datos.ofertas.map(j=>tarjeta(j)).join(''):`<div class="empty"><h2>${datos.total?'Tus filtros no tienen coincidencias':'Busca tus primeras oportunidades'}</h2><p>${datos.total?'Revisa los motivos de exclusión arriba. Puedes ampliar ubicación, tipo o antigüedad, o consultar las alternativas de abajo.':'Completa tu perfil y busca en las fuentes, o añade una oferta por su descripción.'}</p></div>`;
 $('otras').hidden=!(datos.alternativas||[]).length; $('alternativas').innerHTML=(datos.alternativas||[]).map(j=>tarjeta(j,true)).join('');
}
async function filtrar(){const current=++sequence;try{const d=await api('filtrar',prefs());if(current===sequence){datos={...datos,...d};render();}}catch(e){$('estado').textContent=e.message;}}
async function load(){const d=await api('datos');datos={...datos,...d};await filtrar();}
filters.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(filtrar,180);});$('orden').onchange=filtrar;
filters.onsubmit=async e=>{e.preventDefault();const button=filters.querySelector('[type="submit"]');button.disabled=true;$('estado').textContent='Consultando fuentes y descripciones… Puede tardar unos minutos.';try{const p=prefs();const r=await api('buscar',{...p,fuentes:p.fuentes.filter(x=>x!=='manual')});await load();$('estado').textContent=`${r.cantidad} ofertas leídas. ${r.avisos.join(' ')}`;}catch(e){$('estado').textContent=e.message;}finally{button.disabled=false;}};
$('guardar').onclick=async()=>{try{await api('perfil',{...datos.perfil,preferencias:prefs()});await load();$('estado').textContent='Preferencias guardadas en este equipo.';}catch(e){$('estado').textContent=e.message;}};
$('perfilAbrir').onclick=()=>{fill($('perfilForm'),datos.perfil);$('perfil').showModal();};$('importarAbrir').onclick=()=>$('importar').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('perfilForm').onsubmit=async e=>{e.preventDefault();try{await api('perfil',{...datos.perfil,...Object.fromEntries(new FormData(e.target)),preferencias:prefs()});$('perfil').close();await load();}catch(e){alert(e.message);}};
$('importarForm').onsubmit=async e=>{e.preventDefault();try{await api('importar',Object.fromEntries(new FormData(e.target)));$('importar').close();e.target.reset();await load();}catch(e){alert(e.message);}};
document.addEventListener('click',async e=>{const b=e.target.closest('[data-vote]');if(!b)return;b.disabled=true;try{await api('feedback',{id:b.dataset.id,valor:b.dataset.vote});await filtrar();}catch(e){$('estado').textContent=e.message;b.disabled=false;}});
(async()=>{try{datos=await api('datos');fill(filters,datos.perfil.preferencias||{});$('orden').value=datos.perfil.preferencias?.orden||'compatibilidad';render();}catch(e){$('estado').textContent=e.message;}})();
