let datos={perfil:{},ofertas:[]};const $=id=>document.getElementById(id);const filters=$('filtros');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\bingenier(?:o|a|os|as|ia)\b/g,'ingenieria');}
function prefs(){const f=new FormData(filters);return {...Object.fromEntries(f),fuentes:f.getAll('fuentes'),sinfecha:f.has('sinfecha'),desconocidos:f.has('desconocidos'),vencidas:f.has('vencidas')};}
async function api(path,body){const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar');return d;}
async function load(){datos=await api('datos');render();}
function fill(form,values){for(const [k,v]of Object.entries(values)){const controls=form.querySelectorAll(`[name="${k}"]`);controls.forEach(c=>{if(c.type==='checkbox')c.checked=Array.isArray(v)?v.includes(c.value):!!v;else c.value=v??'';});}}
function render(){const p=prefs();let jobs=datos.ofertas.filter(j=>{if(!p.fuentes.includes(j.fuente))return false;if(!p.vencidas&&['vencida','cerrada'].includes(j.estado))return false;if(p.dias&&((j.antiguedad===null&&!p.sinfecha)||(j.antiguedad!==null&&j.antiguedad>+p.dias)))return false;if(!p.sinfecha&&j.antiguedad===null)return false;for(const field of ['ubicacion','modalidad','tipo']){if(p[field]){if(!j[field]){if(!p.desconocidos)return false;}else if(!norm(j[field]).includes(norm(p[field])))return false;}}if(p.sueldo){const comparable=j.moneda==='PEN'&&['mensual','monthly'].includes(j.periodo);if(!comparable||j.salario==null){if(!p.desconocidos)return false;}else if(j.salario<+p.sueldo)return false;}return norm(p.cargo).split(/\s+/).filter(w=>!['de','del','la','el','en','para','y'].includes(w)).every(w=>norm(j.titulo+' '+j.descripcion).includes(w));});const sort=$('orden').value;jobs.sort((a,b)=>sort==='recientes'?(a.antiguedad??Infinity)-(b.antiguedad??Infinity):sort==='cierre'?(a.dias_restantes??Infinity)-(b.dias_restantes??Infinity):(b.puntaje??-1)-(a.puntaje??-1));$('cantidad').textContent=`${jobs.length} visibles · ${datos.ofertas.length} guardadas`;
$('ofertas').innerHTML=jobs.length?jobs.map(j=>`<article class="card"><div class="meta"><span class="source">${esc({'practicas':'Prácticas.pe','convocatorias':'Convocatorias de Trabajo','linkedin':'LinkedIn','manual':'Importada'}[j.fuente])}</span><span>${esc(j.estado)}</span></div><h3>${esc(j.titulo)}</h3><div class="meta"><span>${esc(j.empresa||'Empresa por confirmar')}</span><span>${esc(j.ubicacion||'Ubicación por confirmar')}</span><span>${esc(j.modalidad||'Modalidad por confirmar')}</span><span>${esc(j.tipo)}</span></div><div class="dates"><span>${j.antiguedad===null?'Publicación: fecha desconocida':`Publicado hace ${Math.floor(j.antiguedad)} días`}</span><span>${j.cierre?`Cierre: ${esc(j.cierre.slice(0,10))}${j.dias_restantes>=0?` · quedan ${Math.floor(j.dias_restantes)} días`:''}`:'Cierre: sin fecha confirmada'}</span></div><div class="match">${j.puntaje===null?'Completa tus habilidades para comparar':`${j.puntaje}% de tus habilidades mencionadas`}</div><p class="hint">${j.coincidencias.length?'Encontradas: '+esc(j.coincidencias.join(', ')):''} ${esc(j.aviso)}</p><details><summary>Revisar descripción y requisitos</summary><p class="description">${esc(j.descripcion)}</p></details>${/^https?:\/\//i.test(j.url)?`<a href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">Ver anuncio original</a>`:''}</article>`).join(''):'<div class="empty"><h2>Aquí aparecerán tus oportunidades</h2><p>Configura tus preferencias y busca en las fuentes.<br>También puedes añadir una oferta pegando su descripción.</p><p>No se muestran ofertas de ejemplo.</p></div>';}
filters.addEventListener('input',render);$('orden').onchange=render;
filters.onsubmit=async e=>{e.preventDefault();const button=filters.querySelector('[type="submit"]');button.disabled=true;$('estado').textContent='Consultando las fuentes y revisando fechas… Puede tardar unos minutos.';try{const p=prefs();const r=await api('buscar',{...p,fuentes:p.fuentes.filter(x=>x!=='manual')});await load();$('estado').textContent=`${r.cantidad} ofertas leídas. ${r.avisos.join(' ')}`;}catch(e){$('estado').textContent=e.message;}finally{button.disabled=false;}};
$('guardar').onclick=async()=>{try{await api('perfil',{...datos.perfil,preferencias:prefs()});await load();$('estado').textContent='Preferencias guardadas en este equipo.';}catch(e){$('estado').textContent=e.message;}};
$('perfilAbrir').onclick=()=>{fill($('perfilForm'),datos.perfil);$('perfil').showModal();};$('importarAbrir').onclick=()=>$('importar').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('perfilForm').onsubmit=async e=>{e.preventDefault();try{await api('perfil',{...datos.perfil,...Object.fromEntries(new FormData(e.target)),preferencias:prefs()});$('perfil').close();await load();}catch(e){alert(e.message);}};
$('importarForm').onsubmit=async e=>{e.preventDefault();try{await api('importar',Object.fromEntries(new FormData(e.target)));$('importar').close();e.target.reset();await load();}catch(e){alert(e.message);}};
(async()=>{try{datos=await api('datos');fill(filters,datos.perfil.preferencias||{});render();}catch(e){$('estado').textContent=e.message;}})();
